// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmTRfkcCT00xoCgnXzLPK3-ErxiC-xFBU',
    appId: '1:307266324548:web:31db56f53a3bc495789411',
    messagingSenderId: '307266324548',
    projectId: 'bike-logg',
    authDomain: 'bike-logg.firebaseapp.com',
    storageBucket: 'bike-logg.firebasestorage.app',
    measurementId: 'G-H2E4CEWTW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC10lJfuF2HHgy5eMQKJxZ-E6_rE2N4zzo',
    appId: '1:307266324548:android:8609d0ba88fab165789411',
    messagingSenderId: '307266324548',
    projectId: 'bike-logg',
    storageBucket: 'bike-logg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBwtt-DY8HX-_F93D8TbS5mGX9ojjvFpI',
    appId: '1:307266324548:ios:e56dcee9bc91c5c2789411',
    messagingSenderId: '307266324548',
    projectId: 'bike-logg',
    storageBucket: 'bike-logg.firebasestorage.app',
    iosBundleId: 'com.example.expanseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBwtt-DY8HX-_F93D8TbS5mGX9ojjvFpI',
    appId: '1:307266324548:ios:e56dcee9bc91c5c2789411',
    messagingSenderId: '307266324548',
    projectId: 'bike-logg',
    storageBucket: 'bike-logg.firebasestorage.app',
    iosBundleId: 'com.example.expanseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmTRfkcCT00xoCgnXzLPK3-ErxiC-xFBU',
    appId: '1:307266324548:web:77d4a93341fe8aff789411',
    messagingSenderId: '307266324548',
    projectId: 'bike-logg',
    authDomain: 'bike-logg.firebaseapp.com',
    storageBucket: 'bike-logg.firebasestorage.app',
    measurementId: 'G-HNV2CH03K2',
  );
}
